//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloudRS232
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_DeviceInfo
    {
        public int ID { get; set; }
        public Nullable<int> MerchID { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string SN { get; set; }
        public string Token { get; set; }
        public string QRURL { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> motor1 { get; set; }
        public Nullable<int> motor2 { get; set; }
        public Nullable<int> nixie_tube_type { get; set; }
        public Nullable<int> motor2_coin { get; set; }
        public Nullable<int> motor1_coin { get; set; }
        public Nullable<int> FromDevice { get; set; }
        public Nullable<int> ToCard { get; set; }
        public Nullable<int> SSR { get; set; }
        public Nullable<int> alert_value { get; set; }
    }
}
