//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloudRS232
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GameInfo
    {
        public int GroupID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupType { get; set; }
        public Nullable<int> ReturnCheck { get; set; }
        public Nullable<int> OutsideAlertCheck { get; set; }
        public Nullable<int> ICTicketOperation { get; set; }
        public Nullable<int> NotGiveBack { get; set; }
        public Nullable<int> LotteryMode { get; set; }
        public Nullable<int> OnlyExitLottery { get; set; }
        public Nullable<int> chkCheckGift { get; set; }
        public Nullable<int> AllowElecPush { get; set; }
        public Nullable<int> AllowDecuplePush { get; set; }
        public Nullable<int> GuardConvertCard { get; set; }
        public Nullable<int> ReadCat { get; set; }
        public Nullable<int> AllowRealPush { get; set; }
        public Nullable<int> BanOccupy { get; set; }
        public Nullable<int> StrongGuardConvertCard { get; set; }
        public Nullable<int> AllowElecOut { get; set; }
        public Nullable<int> NowExit { get; set; }
        public Nullable<int> BOPulse { get; set; }
        public Nullable<int> BOLock { get; set; }
        public Nullable<int> AllowRealOut { get; set; }
        public Nullable<int> BOKeep { get; set; }
        public Nullable<int> PushReduceFromCard { get; set; }
        public Nullable<int> PushAddToGame { get; set; }
        public Nullable<int> PushSpeed { get; set; }
        public Nullable<int> PushPulse { get; set; }
        public Nullable<int> PushLevel { get; set; }
        public Nullable<int> PushStartInterval { get; set; }
        public Nullable<int> UseSecondPush { get; set; }
        public Nullable<int> SecondReduceFromCard { get; set; }
        public Nullable<int> SecondAddToGame { get; set; }
        public Nullable<int> SecondSpeed { get; set; }
        public Nullable<int> SecondPulse { get; set; }
        public Nullable<int> SecondLevel { get; set; }
        public Nullable<int> SecondStartInterval { get; set; }
        public Nullable<int> OutSpeed { get; set; }
        public Nullable<int> OutPulse { get; set; }
        public Nullable<int> CountLevel { get; set; }
        public Nullable<int> OutLevel { get; set; }
        public Nullable<int> OutReduceFromGame { get; set; }
        public Nullable<int> OutAddToCard { get; set; }
        public Nullable<int> OnceOutLimit { get; set; }
        public Nullable<int> OncePureOutLimit { get; set; }
        public Nullable<int> SSRTimeOut { get; set; }
        public Nullable<int> ExceptOutTest { get; set; }
        public Nullable<int> ExceptOutSpeed { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> OneDayPureOutLimit { get; set; }
    }
}
