//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloudRS232
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_485_savecoin
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> ICCardID { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> MerchID { get; set; }
    }
}
