//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloudRS232
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCCloudRS232Entities : DbContext
    {
        public XCCloudRS232Entities()
            : base("name=XCCloudRS232Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Base_DeviceInfo> Base_DeviceInfo { get; set; }
        public virtual DbSet<Base_MerchInfo> Base_MerchInfo { get; set; }
        public virtual DbSet<Data_MerchDevice> Data_MerchDevice { get; set; }
        public virtual DbSet<Data_MerchSegment> Data_MerchSegment { get; set; }
        public virtual DbSet<flw_485_coin> flw_485_coin { get; set; }
        public virtual DbSet<flw_485_savecoin> flw_485_savecoin { get; set; }
        public virtual DbSet<t_foods> t_foods { get; set; }
        public virtual DbSet<t_Enum> t_Enum { get; set; }
        public virtual DbSet<flw_food_sale> flw_food_sale { get; set; }
        public virtual DbSet<t_member> t_member { get; set; }
        public virtual DbSet<Data_GameInfo> Data_GameInfo { get; set; }
    }
}
