//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_ticket_exit
    {
        public int ID { get; set; }
        public string Segment { get; set; }
        public string HeadAddress { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<decimal> CoinMoney { get; set; }
        public string UserID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string AuthorID { get; set; }
        public string Note { get; set; }
        public string MacAddress { get; set; }
        public string DiskID { get; set; }
        public string WorkStation { get; set; }
        public Nullable<System.DateTime> ChargeTime { get; set; }
        public Nullable<int> State { get; set; }
        public string PWD { get; set; }
        public Nullable<int> isNoAllow { get; set; }
        public Nullable<int> ICCardID { get; set; }
    }
}
