//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_project_play
    {
        public int ID { get; set; }
        public Nullable<int> BuyID { get; set; }
        public string BarCode { get; set; }
        public string ICCardID { get; set; }
        public Nullable<int> CheckType { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public string InSegment { get; set; }
        public string InHeadAddress { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string OutSegment { get; set; }
        public string OutHeadAddress { get; set; }
    }
}
