//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_project_buy_codelist
    {
        public int ID { get; set; }
        public int BuyID { get; set; }
        public int ProjectID { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public string HeadID { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public Nullable<int> RemainCount { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public Nullable<decimal> CoinValue { get; set; }
    }
}
