//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_checkdate
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> OPTime { get; set; }
        public Nullable<decimal> CheckCash { get; set; }
        public Nullable<decimal> CheckCredit { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string DiskID { get; set; }
        public string WorkStation { get; set; }
        public string Note { get; set; }
    }
}
