//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_project_buy
    {
        public int ID { get; set; }
        public string ICCardID { get; set; }
        public Nullable<int> ProjectRuleID { get; set; }
        public string ProjectRuleName { get; set; }
        public Nullable<int> FreeCoins { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<int> Cash { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Lottery { get; set; }
        public Nullable<decimal> CreditFee { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string WorkStation { get; set; }
        public string MACAddress { get; set; }
        public string DiskID { get; set; }
        public string Comment { get; set; }
    }
}
