//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class flw_schedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> OpenTime { get; set; }
        public string Schedule { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> ShiftTime { get; set; }
        public Nullable<decimal> RealCash { get; set; }
        public Nullable<decimal> RealCredit { get; set; }
        public Nullable<int> RealCoin { get; set; }
        public string MacAddress { get; set; }
        public string DiskID { get; set; }
        public string WorkStation { get; set; }
        public string State { get; set; }
        public string Note { get; set; }
    }
}
