//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_device
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string ConnType { get; set; }
        public string segment { get; set; }
        public string address { get; set; }
        public string MCUID { get; set; }
        public string port_name { get; set; }
        public Nullable<int> baute_rate { get; set; }
        public string parity { get; set; }
        public string ip { get; set; }
        public string WorkStation { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string note { get; set; }
        public Nullable<int> AllowPrint { get; set; }
    }
}
