//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_head
    {
        public string HeadID { get; set; }
        public string GameID { get; set; }
        public string Segment { get; set; }
        public string HeadAddress { get; set; }
        public string State { get; set; }
        public Nullable<int> PushStartInterval { get; set; }
        public Nullable<int> PushSpeed { get; set; }
        public Nullable<int> PushPulse { get; set; }
        public Nullable<int> PushLevel { get; set; }
        public Nullable<int> OutSpeed { get; set; }
        public Nullable<int> OutPulse { get; set; }
        public Nullable<int> CountLevel { get; set; }
        public Nullable<int> OutLevel { get; set; }
        public Nullable<int> BOPulse { get; set; }
        public Nullable<int> ExceptOutTest { get; set; }
        public Nullable<int> ExceptOutSpeed { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> SecondSpeed { get; set; }
        public Nullable<int> SecondPulse { get; set; }
        public Nullable<int> SecondLevel { get; set; }
        public Nullable<int> SecondStartInterval { get; set; }
        public string MCUID { get; set; }
        public Nullable<int> Lock { get; set; }
        public Nullable<int> PrinterGray { get; set; }
        public Nullable<int> OnceOutLimit { get; set; }
        public Nullable<int> OneDayPureOutLimit { get; set; }
        public Nullable<int> BOKeep { get; set; }
        public Nullable<int> BOLock { get; set; }
        public Nullable<int> now_exit { get; set; }
        public Nullable<int> ExitMaxCheck { get; set; }
        public Nullable<int> ReadCat { get; set; }
        public string QRCode { get; set; }
    }
}
