//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_memberlevel
    {
        public int MemberLevelID { get; set; }
        public string MemberLevelName { get; set; }
        public decimal Deposit { get; set; }
        public decimal ExitMoney { get; set; }
        public int ExitCoin { get; set; }
        public decimal ExitPrice { get; set; }
        public string ICColor { get; set; }
        public int Validday { get; set; }
        public decimal OpenFee { get; set; }
        public decimal RenewFee { get; set; }
        public decimal ChangeFee { get; set; }
        public int EarlyRenew { get; set; }
        public int DelayRenew { get; set; }
        public string FreeRate { get; set; }
        public int FreeCoin { get; set; }
        public string BirthdayFree { get; set; }
        public int BirthdayFreeCoin { get; set; }
        public string MustInput { get; set; }
        public int AllowExitCard { get; set; }
        public int AllowExitMoney { get; set; }
        public int FoodID { get; set; }
        public int AllowExitCoinToCard { get; set; }
        public string State { get; set; }
        public int LockHead { get; set; }
        public string type { get; set; }
        public int MinExitCoin { get; set; }
        public int FreeType { get; set; }
        public int FreeNeedWin { get; set; }
    }
}
