//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_member
    {
        public int ICCardID { get; set; }
        public int RootICCardID { get; set; }
        public string MemberID { get; set; }
        public string MemberName { get; set; }
        public string Gender { get; set; }
        public string Birthday { get; set; }
        public string CertificalID { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> JoinTime { get; set; }
        public Nullable<System.DateTime> ModTime { get; set; }
        public Nullable<System.DateTime> RenewTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> MemberLevelID { get; set; }
        public Nullable<int> HasUpDownCoin { get; set; }
        public Nullable<int> HasExitMoney { get; set; }
        public Nullable<int> HasSaleCoin { get; set; }
        public Nullable<int> HasSaveCoin { get; set; }
        public Nullable<int> HasFreeCoin { get; set; }
        public Nullable<int> HasRenew { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string MemberPassword { get; set; }
        public string LeftCode { get; set; }
        public string RightCode { get; set; }
        public string MemberState { get; set; }
        public Nullable<int> RepeatCode { get; set; }
        public string ActiveCode { get; set; }
        public string Note { get; set; }
        public string MemberPhoto { get; set; }
        public Nullable<int> Lock { get; set; }
        public string LockDate { get; set; }
        public Nullable<long> Uid { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RepeatCodeOld { get; set; }
        public Nullable<int> TempCard { get; set; }
        public string LeftHandCode { get; set; }
        public string RightHandCode { get; set; }
        public Nullable<int> Lottery { get; set; }
        public string HandCode { get; set; }
    }
}
