//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_project
    {
        public int id { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public int MemberCoin { get; set; }
        public int TempCoin { get; set; }
        public int IntervalTime { get; set; }
        public int RegretTime { get; set; }
        public int Deposit { get; set; }
        public int DeviceID { get; set; }
        public int PulseCount { get; set; }
        public int Checkout { get; set; }
    }
}
