//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_push_rule
    {
        public int id { get; set; }
        public string game_id { get; set; }
        public Nullable<int> member_level_id { get; set; }
        public string member_level_name { get; set; }
        public string allow_out { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<int> coin { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<System.DateTime> begin_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string allow_in { get; set; }
    }
}
