//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_workstation
    {
        public int ID { get; set; }
        public string WorkStation { get; set; }
        public string MacAddress { get; set; }
        public string DiskID { get; set; }
        public string State { get; set; }
        public string BossAccount { get; set; }
        public string GameAccount { get; set; }
        public Nullable<int> game_online { get; set; }
        public Nullable<int> sender { get; set; }
        public string guid { get; set; }
    }
}
