//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class u_users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string RealName { get; set; }
        public byte[] Photo { get; set; }
        public string UserPwd { get; set; }
        public string Mobile { get; set; }
        public string CertificalID { get; set; }
        public string Note { get; set; }
        public string LeftCode { get; set; }
        public string RightCode { get; set; }
        public Nullable<int> ICCardID { get; set; }
        public Nullable<int> HasUnlock { get; set; }
        public string CreateCardTime { get; set; }
        public string State { get; set; }
        public string JoinTime { get; set; }
        public Nullable<int> HasExitUnlock { get; set; }
    }
}
