//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManagerLog
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UDPRadarHeatLog
    {
        public int Id { get; set; }
        public string RemotePointAddress { get; set; }
        public Nullable<int> RemotePointPort { get; set; }
        public string StoreId { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<bool> HeatSuccess { get; set; }
        public string RequestJson { get; set; }
        public string ResponseJson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
