//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManagerLog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCGameManagerLogEntities : DbContext
    {
        public XCGameManagerLogEntities()
            : base("name=XCGameManagerLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_UDPRadarHeatLog> t_UDPRadarHeatLog { get; set; }
        public virtual DbSet<t_UDPRadarRegisterLog> t_UDPRadarRegisterLog { get; set; }
        public virtual DbSet<t_UDPIndex> t_UDPIndex { get; set; }
        public virtual DbSet<t_UDPRadarNotifyLog> t_UDPRadarNotifyLog { get; set; }
        public virtual DbSet<t_UDPDeviceStateChangeLog> t_UDPDeviceStateChangeLog { get; set; }
        public virtual DbSet<t_UDPSendDeviceControlLog> t_UDPSendDeviceControlLog { get; set; }
        public virtual DbSet<t_UDPDeviceControlLog> t_UDPDeviceControlLog { get; set; }
    }
}
