//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Order
    {
        public string OrderID { get; set; }
        public string StoreID { get; set; }
        public decimal Price { get; set; }
        public decimal Fee { get; set; }
        public int OrderType { get; set; }
        public int PayStatus { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Descript { get; set; }
        public string TradeNo { get; set; }
        public string Mobile { get; set; }
        public int Id { get; set; }
        public string BuyType { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> Coins { get; set; }
    }
}
