//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_datamessage
    {
        public int ID { get; set; }
        public Nullable<int> MessageType { get; set; }
        public string Sender { get; set; }
        public Nullable<int> SenderType { get; set; }
        public string Receiver { get; set; }
        public Nullable<int> ReceiverType { get; set; }
        public Nullable<int> ChannelType { get; set; }
        public string Data { get; set; }
        public Nullable<int> ReadFlag { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
