//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_device
    {
        public int Id { get; set; }
        public string TerminalNo { get; set; }
        public string DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceType { get; set; }
        public Nullable<int> StoreType { get; set; }
        public string StoreId { get; set; }
        public string Note { get; set; }
    }
}
