//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_store
    {
        public int id { get; set; }
        public string companyname { get; set; }
        public string province { get; set; }
        public string address { get; set; }
        public string boss { get; set; }
        public string phone { get; set; }
        public string telphone { get; set; }
        public string client_level { get; set; }
        public string clienttype { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<System.DateTime> power_due_date { get; set; }
        public string note { get; set; }
        public string parentid { get; set; }
        public string developer { get; set; }
        public string store_password { get; set; }
        public string store_dbname { get; set; }
        public Nullable<decimal> wxfee { get; set; }
        public Nullable<int> StoreType { get; set; }
        public string Token { get; set; }
        public Nullable<int> State { get; set; }
        public string openId { get; set; }
        public int StoreDBDeployType { get; set; }
    }
}
