//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UserRegister
    {
        public int ID { get; set; }
        public string Mobile { get; set; }
        public string StoreId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> AuditingTime { get; set; }
        public string AuditingUser { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
    }
}
