//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCGameManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_usertoken
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public string Mobile { get; set; }
        public string StoreId { get; set; }
        public string StoreName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> XCGameUserId { get; set; }
    }
}
