//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_UserInfo
    {
        public int UserID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public string LogName { get; set; }
        public string LogPassword { get; set; }
        public string OpenID { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string ICCardID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Auditor { get; set; }
        public Nullable<System.DateTime> AuditorTime { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<int> AuthorTempID { get; set; }
        public string UnionID { get; set; }
        public Nullable<int> SwitchMerch { get; set; }
        public Nullable<int> SwitchStore { get; set; }
        public Nullable<int> SwitchWorkstation { get; set; }
    }
}
