//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_MerchantInfo
    {
        public string MerchID { get; set; }
        public Nullable<int> MerchType { get; set; }
        public string MerchAccount { get; set; }
        public Nullable<int> MerchStatus { get; set; }
        public string MerchPassword { get; set; }
        public Nullable<int> MerchTag { get; set; }
        public string WxOpenID { get; set; }
        public string WxUnionID { get; set; }
        public string Mobil { get; set; }
        public string MerchName { get; set; }
        public Nullable<int> AllowCreateCount { get; set; }
        public Nullable<int> AllowCreateSub { get; set; }
        public Nullable<int> CreateType { get; set; }
        public string CreateUserID { get; set; }
        public string Comment { get; set; }
    }
}
