//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_StoreInfo
    {
        public string StoreID { get; set; }
        public string ParentID { get; set; }
        public string MerchID { get; set; }
        public string StoreName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> AuthorExpireDate { get; set; }
        public string AreaCode { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public string Contacts { get; set; }
        public string IDCard { get; set; }
        public Nullable<System.DateTime> IDExpireDate { get; set; }
        public string Mobile { get; set; }
        public string ShopSignPhoto { get; set; }
        public string LicencePhoto { get; set; }
        public string LicenceID { get; set; }
        public Nullable<System.DateTime> LicenceExpireDate { get; set; }
        public string BankType { get; set; }
        public string BankCode { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> SelttleType { get; set; }
        public Nullable<int> SettleID { get; set; }
        public Nullable<int> StoreState { get; set; }
    }
}
