//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_DeviceInfo
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public string DeviceName { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> CmdType { get; set; }
        public string segment { get; set; }
        public string Address { get; set; }
        public string MCUID { get; set; }
        public string port_name { get; set; }
        public Nullable<int> baute_rate { get; set; }
        public Nullable<int> parity { get; set; }
        public string IPAddress { get; set; }
        public string WorkStation { get; set; }
        public Nullable<int> DeviceStatus { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string note { get; set; }
        public Nullable<int> AllowPrint { get; set; }
    }
}
