//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_MemberInfo
    {
        public int ID { get; set; }
        public string Wechat { get; set; }
        public string QQ { get; set; }
        public string IMME { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string IDCard { get; set; }
        public string Mobile { get; set; }
        public string EMail { get; set; }
        public string LeftHandCode { get; set; }
        public string RightHandCode { get; set; }
        public Nullable<int> MemberState { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Photo { get; set; }
        public string Note { get; set; }
    }
}
