//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Card_Right
    {
        public int ID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> AllowPush { get; set; }
        public Nullable<int> AllowOut { get; set; }
        public Nullable<int> AllowExitCoin { get; set; }
        public Nullable<int> AllowSaleCoin { get; set; }
        public Nullable<int> AllowSaveCoin { get; set; }
        public Nullable<int> AllowFreeCoin { get; set; }
        public Nullable<int> AllowRenew { get; set; }
    }
}
