//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Storage_Record
    {
        public int ID { get; set; }
        public Nullable<int> StorageID { get; set; }
        public Nullable<int> StorageFlag { get; set; }
        public Nullable<int> StorageCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Note { get; set; }
    }
}
