//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Food_Level
    {
        public int ID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> MemberLevelID { get; set; }
        public string Week { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<decimal> VIPPrice { get; set; }
        public Nullable<decimal> ClientPrice { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> day_sale_count { get; set; }
        public Nullable<int> member_day_sale_count { get; set; }
        public Nullable<int> AllowCoin { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<int> AllowPoint { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> AllowLottery { get; set; }
        public Nullable<int> Lottery { get; set; }
        public Nullable<int> PeriodType { get; set; }
    }
}
