//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_MemberLevel
    {
        public int MemberLevelID { get; set; }
        public string StoreID { get; set; }
        public string MemberLevelName { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> ExitMoney { get; set; }
        public Nullable<int> ExitCoin { get; set; }
        public Nullable<decimal> ExitPrice { get; set; }
        public string CardUIURL { get; set; }
        public Nullable<int> Validday { get; set; }
        public Nullable<int> FreeRate { get; set; }
        public Nullable<int> FreeCoin { get; set; }
        public Nullable<int> BirthdayFree { get; set; }
        public Nullable<int> BirthdayFreeCoin { get; set; }
        public Nullable<int> NeedAutor { get; set; }
        public Nullable<int> MustInput { get; set; }
        public Nullable<int> AllowExitCard { get; set; }
        public Nullable<int> AllowExitMoney { get; set; }
        public Nullable<int> AllowExitCoinToCard { get; set; }
        public Nullable<int> AllowSubProject { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> LockHead { get; set; }
        public Nullable<int> MinExitCoin { get; set; }
        public Nullable<int> FreeType { get; set; }
        public Nullable<int> FreeNeedWin { get; set; }
    }
}
