//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GivebackRule
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> MemberLevelID { get; set; }
        public Nullable<int> BackMin { get; set; }
        public Nullable<int> BackMax { get; set; }
        public Nullable<int> BackScale { get; set; }
        public Nullable<int> ExitCardMin { get; set; }
        public Nullable<int> AllowBackPrincipal { get; set; }
        public Nullable<int> Backtype { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> AllowContainToday { get; set; }
    }
}
