//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Member_Card
    {
        public int ID { get; set; }
        public string ICCardID { get; set; }
        public Nullable<int> ParentCard { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> CardShape { get; set; }
        public Nullable<int> CardLimit { get; set; }
        public Nullable<int> AllowIn { get; set; }
        public Nullable<int> AllowOut { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> MemberLevelID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string LastStore { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> RepeatCode { get; set; }
        public Nullable<long> UID { get; set; }
        public Nullable<int> CardStatus { get; set; }
    }
}
