//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Head
    {
        public int ID { get; set; }
        public string HeadID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> GameIndexID { get; set; }
        public string Segment { get; set; }
        public string HeadName { get; set; }
        public string HeadAddress { get; set; }
        public Nullable<int> State { get; set; }
        public string MCUID { get; set; }
        public Nullable<int> Lock { get; set; }
        public string BarCode { get; set; }
    }
}
