//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_ProjectInfo
    {
        public int ID { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> ProjectStatus { get; set; }
        public Nullable<int> FeeType { get; set; }
        public Nullable<int> FeeCycle { get; set; }
        public Nullable<int> FeeDeposit { get; set; }
        public Nullable<int> SignOutEN { get; set; }
        public Nullable<int> WhenLock { get; set; }
        public Nullable<int> RegretTime { get; set; }
        public string Note { get; set; }
    }
}
