//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GoodStock_Record
    {
        public int ID { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> GoodID { get; set; }
        public Nullable<int> DepotID { get; set; }
        public Nullable<int> StockFlag { get; set; }
        public Nullable<int> StockCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Note { get; set; }
    }
}
