//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_GameInfo_Ext
    {
        public int ID { get; set; }
        public Nullable<int> GameID { get; set; }
        public string GameCode { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> Evaluation { get; set; }
        public Nullable<int> Price { get; set; }
        public string MerchID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> ValidFlag { get; set; }
    }
}
