//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Game_StockInfo
    {
        public int ID { get; set; }
        public Nullable<int> GameIndex { get; set; }
        public Nullable<int> GoodID { get; set; }
        public Nullable<int> DeportID { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
        public Nullable<System.DateTime> InitialTime { get; set; }
        public Nullable<int> InitialCount { get; set; }
        public Nullable<int> RemainCount { get; set; }
        public string Note { get; set; }
    }
}
