//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_DigitCoin
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public string ICardID { get; set; }
        public Nullable<int> DigitLevelID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
    }
}
