//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dict_System
    {
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string DictKey { get; set; }
        public string DictValue { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> Enabled { get; set; }
        public string MerchID { get; set; }
        public Nullable<int> DictLevel { get; set; }
    }
}
