//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Lottery
    {
        public int ID { get; set; }
        public Nullable<int> WorkType { get; set; }
        public string GameID { get; set; }
        public string HeadID { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> LotteryCount { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> GoodsFlwID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string WorkStation { get; set; }
    }
}
