//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Giveback
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> PICCardID { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string WorkStation { get; set; }
        public Nullable<System.DateTime> ExitRealTime { get; set; }
        public Nullable<int> ExitAuthorID { get; set; }
        public Nullable<int> ExitUserID { get; set; }
        public Nullable<int> ExitScheduleID { get; set; }
        public string ExitWorkStation { get; set; }
        public Nullable<decimal> ExitMoney { get; set; }
        public Nullable<int> ExitAllCoins { get; set; }
        public Nullable<int> ExitRealCoins { get; set; }
        public Nullable<int> ExitBaseCoins { get; set; }
        public Nullable<int> ExitState { get; set; }
        public Nullable<int> ExitMin { get; set; }
        public string ExitBackPrincipal { get; set; }
        public Nullable<decimal> WinMoney { get; set; }
        public Nullable<int> MayCoins { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
