//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Transfer
    {
        public int id { get; set; }
        public Nullable<int> ExitFlwID { get; set; }
        public Nullable<int> CardIDOut { get; set; }
        public Nullable<int> CardIDIn { get; set; }
        public Nullable<int> TransferType { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<int> BalanceOut { get; set; }
        public Nullable<int> BalanceIn { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> UserID { get; set; }
        public string WorkStation { get; set; }
        public Nullable<int> ScheduleID { get; set; }
    }
}
