//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Coin_Exit
    {
        public int ID { get; set; }
        public Nullable<int> FlowType { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> MemberLevelID { get; set; }
        public Nullable<int> Coins { get; set; }
        public Nullable<decimal> CoinMoney { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<System.DateTime> RealTime { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public string Note { get; set; }
        public string WorkStation { get; set; }
    }
}
