//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Good_Detail
    {
        public int ID { get; set; }
        public string OrderID { get; set; }
        public string Barcode { get; set; }
        public string GoodsName { get; set; }
        public Nullable<decimal> AllPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> AllPoint { get; set; }
        public Nullable<int> AllCoin { get; set; }
        public Nullable<int> AllLottery { get; set; }
    }
}
