//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Project_BuyDetail
    {
        public int ID { get; set; }
        public Nullable<int> FoodSaleID { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ParentID { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> SaleTime { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public Nullable<int> RemainCount { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
