//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Game_WinPrize
    {
        public int ID { get; set; }
        public Nullable<int> GameIndex { get; set; }
        public Nullable<int> GoodID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> WinTime { get; set; }
        public Nullable<int> HeadIndex { get; set; }
        public Nullable<decimal> GoodPrice { get; set; }
    }
}
