//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_Order
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public string OrderID { get; set; }
        public Nullable<int> FoodCount { get; set; }
        public Nullable<int> GoodCount { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<int> OrderSource { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<decimal> PayCount { get; set; }
        public Nullable<decimal> RealPay { get; set; }
        public Nullable<decimal> FreePay { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public string WorkStation { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> SettleFlag { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> PayFee { get; set; }
    }
}
