//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flw_CouponUse
    {
        public int ID { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> OrderFlwID { get; set; }
        public Nullable<int> CouponID { get; set; }
        public Nullable<int> CouponCode { get; set; }
        public Nullable<decimal> FreeMoney { get; set; }
        public Nullable<int> Coins { get; set; }
    }
}
