//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search_Template_Detail
    {
        public int ID { get; set; }
        public Nullable<int> TempID { get; set; }
        public string FieldName { get; set; }
        public string Title { get; set; }
        public string Datatype { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> ShowColume { get; set; }
        public Nullable<int> ShowSearch { get; set; }
        public Nullable<int> DictID { get; set; }
    }
}
