//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_CheckDate
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string StoreID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> AliPay { get; set; }
        public Nullable<decimal> Wechat { get; set; }
        public Nullable<decimal> BankPOS { get; set; }
        public Nullable<int> CardNumberCount { get; set; }
        public Nullable<int> CardCoins { get; set; }
        public Nullable<decimal> CardDepositCount { get; set; }
        public Nullable<int> ICPushCoins { get; set; }
        public Nullable<int> DigiteCoins { get; set; }
        public Nullable<int> OutCoins { get; set; }
        public Nullable<int> LotteryCount { get; set; }
        public Nullable<int> LotteryCoins { get; set; }
        public Nullable<int> ChargeCoins { get; set; }
        public Nullable<int> NoChargeCoins { get; set; }
    }
}
