//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_GameTotal
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string GameiD { get; set; }
        public Nullable<int> CoinFromCard { get; set; }
        public Nullable<int> CoinFromDigit { get; set; }
        public Nullable<int> CoinFromReal { get; set; }
        public Nullable<int> CoinFromFree { get; set; }
        public Nullable<int> OutFromCard { get; set; }
        public Nullable<int> OutFromPrint { get; set; }
        public Nullable<int> OutFromReal { get; set; }
    }
}
