//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCCloudService.Model.XCCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class XC_WorkInfo
    {
        public int WorkID { get; set; }
        public Nullable<int> WorkType { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<System.DateTime> SenderTime { get; set; }
        public Nullable<int> WorkState { get; set; }
        public string WorkBody { get; set; }
        public Nullable<int> AuditorID { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string AuditBody { get; set; }
    }
}
